name: Multiverse-Core
main: com.onarandombox.MultiverseCore.MultiverseCore
authors: ['Rigby', 'fernferret', 'lithium3141', 'main--', 'dumptruckman']
website: 'https://dev.bukkit.org/projects/multiverse-core'
version: maven-version-number
commands:
  mv:
    description: Generic Multiverse Command
    usage: /<command>
  mvcreate:
    description: World create command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Creates a world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Creates a world called 'hellworld' with a NETHER environment.
  mvc:
    description: World create command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Creates a world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Creates a world called 'hellworld' with a NETHER environment.
  mvimport:
    description: World import command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Imports an existing world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Imports an existing world called 'hellworld' with a NETHER environment.
  mvim:
    description: World import command
    usage: |
            /<command> <world> <environment>
            /<command> creative normal -- Imports an existing world called 'creative' with a NORMAL environment.
            /<command> hellworld nether -- Imports an existing world called 'hellworld' with a NETHER environment.
  mvremove:
    description: World remove command
    usage: |
            /<command> <world>
  mvdelete:
    description: World delete command
    usage: |
            /<command> <world>
  mvunload:
    description: World unload command
    usage: |
            /<command> <world>
  mvmodify:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvmset:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvmadd:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvmremove:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvmclear:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvm:
    description: Modify the settings of an existing world
    usage: |
            /<command> <world> <option>:<value>
            /<command> creative pvp:false -- Turns off PVP in the 'creative' world.
  mvtp:
    description: Command to teleport between Worlds
    usage: |
            /<command> <world>[:spawn]
            Example: /<command> creative - Teleports you to the relevant location in the 'creative' world.
            Example: /<command> creative:spawn - Teleports you to the spawn of the 'creative' world.
  mvlist:
    description: Print list of loaded Worlds
    usage: |
            /<command> [environment]
            Example: /<command> NETHER - Shows all NETHER Worlds.
            Example: /<command> NORMAL - Shows all NORMAL Worlds.
  mvl:
    description: Print list of loaded Worlds
    usage: |
            /<command> [environment]
            Example: /<command> NETHER - Shows all NETHER Worlds.
            Example: /<command> NORMAL - Shows all NORMAL Worlds.
  mvsetspawn:
    description: Set the spawn area for a particular world
    usage: /<command> -- Sets the spawn area of the current world to your location.
  mvset:
    description: Set the spawn area for a particular world
    usage: /<command> -- Sets the spawn area of the current world to your location.
  mvss:
    description: Set the spawn area for a particular world
    usage: /<command> -- Sets the spawn area of the current world to your location.
  mvspawn:
    description: Teleport to the spawn area
    usage: /<command> -- Teleports you to the spawn area of your current world.
  mvs:
    description: Teleport to the spawn area
    usage: /<command> -- Teleports you to the spawn area of your current world.
  mvcoord:
    description: Display World, Coordinates, Direction & Compression for a world.
    usage: |
            /<command> [world]
            /<command> -- Shows the relevant coordinates in your current world.
            /<command> creative -- Shows the relevant coordinates if you were in the 'creative' world.
  mvc:
    description: Display World, Coordinates, Direction & Compression for a world.
    usage: |
            /<command> [world]
            /<command> -- Shows the relevant coordinates in your current world.
            /<command> creative -- Shows the relevant coordinates if you were in the 'creative' world.
  mvwho:
    description: Display online users per world.
    usage: |
            /<command> [world]
            /<command> -- Shows who is online in each world.
            /<command> creative -- Shows who is online in the 'creative' world.
  mvw:
    description: Display online users per world.
    usage: |
            /<command> [world]
            /<command> -- Shows who is online in each world.
            /<command> creative -- Shows who is online in the 'creative' world.
  mvreload:
    description: Reload Configuration files.
    usage: /<command>
  mvr:
    description: Reload Configuration files.
    usage: /<command>
  mvpurge:
    description: Purge the targetted world of creatures.
    usage: |
            /<command> [world] [creatures]
            /<command> -- Purges the players world of all creatures.
            /<command> creative * -- Purges the creative world of all Creatures.
            /<command> creative creeper -- Purges the creative world of all CREEPERS.
  mvconfirm:
    description: Confirms sensitive decisions like deleting a world.
    usage: |
            /<command>
  mvinfo:
    description: Gets world info.
    usage: |
            /<command> [world]
  mvi:
    description: Gets world info.
    usage: |
            /<command> [world]
  mvenv:
    description: Tells the user all possible environment types.
    usage: |
            /<command>
  mvv:
    description: Prints out version info.
    usage: |
            /<command>
  mvversion:
    description: Prints out version info.
    usage: |
            /<command>
  mvco:
    description: Displays the player's coordinates.
    usage: |
            /<command>
  mvh:
    description: Displays the Multiverse Help.
    usage: |
            /<command>
  mvsearch:
    description: Displays the Multiverse Help.
    usage: |
            /<command>
  mvhelp:
    description: Displays the Multiverse Help.
    usage: |
            /<command>
  mvdebug:
    description: Turns on debugging.
    usage: |
            /<command>
  mvgenerators:
    description: Displays all found world generators.
    usage: |
            /<command>
  mvgens:
    description: Displays all found world generators.
    usage: |
            /<command>
  mvload:
    description: Loads a world into Multiverse.
    usage: |
            /<command> {WORLD}
  mvregen:
    description: Regenerates a world Multiverse already knows about.
    usage: |
            /<command> {WORLD}
  mvscript:
    description: Runs a script from the Multiverse scripts directory.
    usage: |
            /<command> {script} [target]
  mvclone:
    description: World clone command
    usage: |
            /<command> <world> <environment>
            /<command> creative grieftastic -- Creates a world called 'grieftastic' exactly identical to the world 'creative'.
  mvsilent:
    description: Reduces startup messages
    usage: |
            /<command> [true|false]
  
  mvgamerule:
    description: Sets a gamerule.
    usage: |
            /<command> {RULE} {VALUE} [WORLD]
  mvrule:
    description: Sets a gamerule.
    usage: |
            /<command> {RULE} {VALUE} [WORLD]
  mvgamerules:
    description: Lists the gamerules.
    usage: |
            /<command> [WORLD]
  mvrules:
    description: Lists the gamerules.
    usage: |
            /<command> [WORLD]