############################################################
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
############################################################

# If you want to use special characters in this document, such as accented letters, you MUST save the file as UTF-8, not ANSI.
# If you receive an error when Multismarts loads, ensure that:
#   - No tabs are present: YAML only allows spaces.
#   - Indents are correct: YAML hierarchy is based entirely on indentation.
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe).
#   - Text with symbols is enclosed in single or double quotation marks.

############################################################
# +------------------------------------------------------+ #
# |                      VScoreboard                     | #
# +------------------------------------------------------+ #
############################################################

# If you need help about Color & Formatting codes check this page: https://minecraft.gamepedia.com/Formatting_codes
# If you want to return to default, you must delete this config.yml and load the plugin in your server for generate a new config.yml

#+-----------------------------------------------------------+
    # Timer meanings (Value = seconds)
      # Set_time: How many seconds for setting the scoreboard when a player connects.
      # Refresh_time: How many seconds until next refresh (Very fast refresh can generate problems).
    
Timer:
    Set_time: 1     
    Refresh_time: 5 
#+-----------------------------------------------------------+
   # Scoreboard_structure meanings (Value = type of structure)
    # Only integer values between 1 and 5.
    # You'll understand what is a section if you see "Scoreboard_sections" below.
      # 1 = 1 section in board.  -> (Section1)
      # 2 = 2 sections in board. -> (Section1)+(Section2)
      # 3 = 3 sections in board. -> (Section1)+(Section2)+(Section3)
      # 4 = 4 sections in board. -> (Section1)+(Section2)+(Section3)+(Section4)
      # 5 = 5 sections in board. -> (Section1)+(Section2)+(Section3)+(Section4)+(Section5)
      
      
Scoreboard_structure:

    Structure: 3
#+-----------------------------------------------------------+
# Variables that you can use anywhere:
        #   |Server variables|
 
            # <numberplayers> = Number of online players.
            # <player> = User's name.
            # <servername> = Server's name described in file server.properties
            # <worldname> = World's name.
    
        #   |PvP variables|
 
            # <kills> = Player's amount of kills.
            # <deaths> = Player's amount of deaths.
            # <kdratio> = Player's kill / death ratio.

        #   |Economy variables|
 
            #  <balance> = User's balance (Requires economy plugin).
             
Scoreboard_sections:
    #Don't use the same text in various Texts. Bad -> Text1a: "Hello" Text2a: "Hello" | Good -> Text1a: "Hello" Text2a : "Hello&f"
    Title: "&6&l<servername>"
#+-------------------------------------------------+
#                    |SECTION 1|
    Sectionspacer1: "&1" 
    Section1a: "» &4User:"
    Section1b: "» <player>"
#+-------------------------------------------------+   
#                    |SECTION 2|
    Sectionspacer2: "&2"
    Section2a: "» &4Players:"
    Section2b: "» <numberplayers> online"
#+-------------------------------------------------+  
#                    |SECTION 3|
    Sectionspacer3: "&3"     
    Section3a: "» &4Money:"
    Section3b: "» <balance> $"
#+-------------------------------------------------+   
#                    |SECTION 4|
    Sectionspacer4: "&4"  
    Section4a: "» &4Kills:"
    Section4b: "» <kills>&5"
#+-------------------------------------------------+
#                    |SECTION 5|
    Sectionspacer5: "&5"
    Section5a: "» &4Deaths:"
    Section5b: "» <deaths>"
 
    

  