#_ENCENDIDO Y APAGADO____________________________
  Multismarts:
      Estado: true
      Modulos:
          Vago: true
          Vconomy: true
          
#________________________________________________