#_EVA.MULTISMARTS________________________________
  Multismarts:
      Status: true
      Modules:
          Vago: true
          Vconomy: true
          VScoreboard: true
          Ejemplos: true
          
#________________________________________________