##_ENCENDIDO Y APAGADO____________________________
#  Activado:
#      Estado: true
#      Mensaje: "Activado"
#  Desactivado:
#      Estado: true
#      Mensaje: "Desactivado"
##________________________________________________
#
##_COMANDOS_______________________________________
#  Hola:
#      Estado: true
#      Mensaje: "&3Buenos días Jugador_nombre"
##________________________________________________
#
##_FUNCIONALIDADES________________________________
#  Jugador_acceso:
#      Estado: true
#      Mensaje: "&9Yieeee que pasa Jugador_nombre"
#  Jugador_movimiento:
#      Estado: false
#      Experiencia: 100000
##________________________________________________