#_EVA.MULTISMARTS________________________________
  Multismarts:
      Estado: true
      Módulos:
          Vago: true
          Vconomy: true
          Ejemplos: true
          
#________________________________________________