name: ${project.name}
author: AdriiGamerYT, ViC y Elferic
version: ${project.version}
main: com.eva.multismarts.Main
description: ${project.description}
depends: Vault
commands:
    vscoreboard:
        description: Cierra el scoreboard mostrado a la derecha de la pantalla
        usage: /vscoreboard
    vreset:
        description: Resetea el dinero que tiene un usuario determinado.
        usage: /vreset
    vpay:
        description: Transfiere dinero de tu cuenta a un usuario determinado.
        usage: /vpay
    vgive:
        description: Proporciona la cantidad de dinero que determines a un usuario determinado.
        usage: /vgive
    vtake:
        description: Quita la cantidad de dinero que determines a un usuario determinado.
        usage: /vtake
    vmoney:
        description: Muestra la cantidad de dinero que tiene un jugador determinado.
        usage: /vmoney
    vreceive:
        description: Proporciona la cantidad de dinero que solicites.
        usage: /vreceive
        
    espawn:
        description: genera la configuración del módulo ESpawn
        usage: /espawn
    #Ejemplo registrar comando
    Hola:
        description: Este comando dará los buenos días.
        usage: /hola