name: ${project.name}
author: AdriiGamerYT, ViC y Elferic
version: ${project.version}
main: com.eva.multismarts.Main
description: ${project.description}
commands:
    
    #Ejemplo registrar comando
    Hola:
        description: Este comando dará los buenos días.
        usage: /hola