name: ${project.name}
author: AdriiGamerYT, ViC y Elferic
version: ${project.version}
main: com.eva.multismarts.Main
description: ${project.description}
depends: Vault
commands:
    vgive:
        description: Proporciona la cantidad de dinero que determines a un usuario determinado.
        usage: /vgive
    vtake:
        description: Quita la cantidad de dinero que determines a un usuario determinado.
        usage: /vtake
    vmoney:
        description: Muestra la cantidad de dinero que tiene un jugador determinado.
        usage: /vmoney
    vreceive:
        description: Proporciona la cantidad de dinero que solicites.
        usage: /vreceive
    Vago:
        description: No hace nada...
        usage: /vago
    #Ejemplo registrar comando
    Hola:
        description: Este comando dará los buenos días.
        usage: /hola